#!/usr/bin/env python3
"""
Debug script to check what the generated CADQuery code looks like
"""

# From the logs, I can see the generated code is 302 characters
# Let me create a simple test to see what typical Bedrock-generated code looks like

print("Typical CADQuery code generated by Bedrock might look like:")
print()

sample_code = """
import cadquery as cq

result = (cq.Workplane("XY")
    .circle(100)
    .extrude(20)
    .faces(">Z")
    .workplane()
    .circle(10)
    .cutThru())
"""

print("Sample inline code (no variables):")
print(sample_code)
print()

print("This explains why parameter extraction fails - no variables to extract!")
print()
print("We need to:")
print("1. Check if design parameters node was created")
print("2. If not, we need to add variables to the generated code")
print("3. Or modify parameter editing to work with inline values")